CREATE DATABASE IF NOT EXISTS gateway_db;
CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS room_db;
CREATE DATABASE IF NOT EXISTS booking_db;
CREATE DATABASE IF NOT EXISTS payment_db;

GRANT ALL PRIVILEGES ON *.* TO 'hotel_user'@'%';
FLUSH PRIVILEGES;
